// <auto-generated />
namespace Order.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class od_init : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(od_init));
        
        string IMigrationMetadata.Id
        {
            get { return "201711251337372_od_init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
