// <auto-generated />
namespace Stock.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class si_update_2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(si_update_2));
        
        string IMigrationMetadata.Id
        {
            get { return "201712020205553_si_update_2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
